### ISSUE TITLE
노드카카오가 프론트엔드에서도 구동이 되나요?

### ISSUE THREAD

**Issue by rycont** [thoratica/CocoaTalk#1]
안녕하세요! 저도 비슷한 프로젝트를 진행중입니다. 여러 방향으로 연구를 해보고 있고, 그중 노드카카오를 프론트엔드에서 바로 실행하는 방법도 시도를 해보았지만, CORS문제와 여러 라이브러리 호환 이슈때문에 패스하고 다른 방법(노드로 백엔드 분리)을 택했습니다. 혹시 프론트엔드에서 구동이 가능하다면, 방법을 공유해주실 수 있을까 해서 이슈 남깁니다 :)

아, 그리고 제 프로젝트에 대해 더 궁금한 점이 있으시다면 reactdev@kakao.com, 혹은 텔레그램 @rycont (t.me/rycont)로 연락 부탁드립니다. 방향성이 비슷해서, 같이 논의하면서 개발해도 좋을것같아요.

**Comment by cog25** [comment]
해당 프로젝트는 아직 프론트엔드만 계발되었습니다. 그리고 본 프로젝트는 `electron`을 통한 앱으로 계획중이십니다.  

--------------
~~그리고 디미고 다니시는군요, 개인적으로 합격 팁같은것좀 주실 수 있을까요?~~
